style = "conventional"
subject_capitalized = false
subject_length = 72
subject_not_punctuated = true
imperative_subject = true
no_fixup = true
no_wip = true
line_length = 72
allowed_types = [
    "feat",
    "fix",
    "docs",
    "style",
    "refactor",
    "perf",
    "test",
    "build",
    "ci",
    "chore",
    "revert",
]
merge_commit = true
